"""OpenDART — Korea's leadership spine, which is the report NAME and not a code.

South Korea's Financial Supervisory Service runs DART, the mandatory disclosure
registry, and exposes it through the keyed OpenDART API. This collector reads
ONE endpoint, the date-ranged disclosure list:

    https://opendart.fss.or.kr/api/list.json
        ?crtfc_key=...&bgn_de=YYYYMMDD&end_de=YYYYMMDD
        &pblntf_detail_ty=E005|I001&page_no=N&page_count=100

WHAT WAS LOOKED FOR AND WHAT IS ACTUALLY THERE. The India unlock was SEBI's
mandated Regulation 30 CATEGORY: a machine-readable label on every officer
change, the same shape as Item 5.02 of a US Form 8-K. Korea's published API
list was walked end to end on 2026-07-29 (six groups, 84 endpoints, from
`https://opendart.fss.or.kr/guide/main.do?apiGrpCd=DS001..DS006`) looking for
the equivalent. It does not exist at code level:

  * **`pblntf_detail_ty` stops one level too coarse.** The whole typed taxonomy
    is 10 types and ~60 detail codes. Every Korea Exchange timely disclosure —
    supply contracts, dividends, buybacks, CEO changes, litigation — arrives
    under the single code `I001` (수시공시). There is no `I001-3-a`. That is
    the Form 6-K problem: a filing type with no item taxonomy inside it.
  * **The 주요사항보고서 (major report) family carries no officer item at all.**
    All 36 endpoints in group DS005 were read: insolvency, capital raises,
    buybacks, mergers, divisions, asset transfers, business suspension. Not one
    is an appointment or a departure. The brief that asked for this connector
    named that family as a candidate; it is a dead end, measured rather than
    assumed.
  * **The periodic-report endpoints ARE snapshots, exactly as feared.**
    `exctvSttus.json` (임원현황) returns every sitting officer as of
    `stlm_dt` — name, position, tenure as free text ("3년 6개월"), term expiry.
    `empSttus.json` (직원현황) returns headcount by division and gender.
    Neither states that anybody was appointed, and neither carries an
    appointment DATE. Turning them into events would mean diffing year N
    against year N-1 and stamping the difference with a date the source never
    stated, which "no source URL, no record" and "the model never invents a
    number" both forbid. They are refused. See REFUSED_ENDPOINTS.

WHAT DOES WORK: the exchange's own report NAME is a fixed vocabulary. Measured
unauthenticated against DART's public search (`dart.fss.or.kr/dsab007/`, which
robots.txt permits) over 2026-05-01 to 2026-07-29, 8,363 disclosures:

    독립이사의선임ㆍ해임또는중도퇴임에관한신고   150   (detail type E005)
    대표이사변경                                  79   (inside I001)
    대표이사(대표집행임원)변경(안내공시)          28   (inside I001)
    대표집행임원변경                               4   (inside I001)
                                              ------
                                                 261  in 90 days, ~1,060/year

8,211 `I001` filings in that window collapse into 360 DISTINCT names, and the
four above recur identically. These are KRX's own form titles, generated by the
exchange's filing system, not sentences a company composed — the same kind of
value as BSE's `SUBCATNAME`. `E005` is better still: one detail code whose every
row (150 of 150) carries one name, and that name says what happened —
appointment, dismissal or early retirement of an independent director.

So Korea is real but NARROW. India files ~13,000 leadership disclosures a year
because Regulation 30 covers every director and every key managerial person.
Korea's mandatory timely-disclosure item covers the REPRESENTATIVE DIRECTOR
(the CEO) and, separately, independent directors. Ordinary inside directors are
elected at a shareholder meeting and appear only in the meeting's result, which
is untyped prose. That gap is the honest price and it is not closable from here.

THE DIRECTION IS NOT IN THE SOURCE, so no row claims one. `대표이사변경` says
"change of representative director" and `독립이사의선임ㆍ해임또는중도퇴임에관한신고`
names all three possibilities in one title. Neither separates a joiner from a
leaver, so every row here is `neutral`, as India's departures already are.
`displacement` is never used: one officer leaving is a change of leadership, not
a workforce reduction, and workforce reductions are the sibling tracker's scope.

FOUR TRAPS, each found by reading the API or fetching a real filing.

1. **A missing key is an HTTP 302 to an HTML page, and a BAD key is an HTTP 200.**
   Verified live on 2026-07-29 without any credential: `list.json` with no
   `crtfc_key` returns 302 and an HTML error document, while a syntactically
   valid but unregistered key returns `200 {"status":"010"}`. So neither
   "status_code == 200" nor "the body parsed as JSON" means success — the
   `status` field is the only authority. This matters here more than usual:
   CLAUDE.md records that mapping a MISSING GitHub secret sets the environment
   variable to empty string, which is exactly how a leadership dispatch once
   went green having stored nothing. An empty key is refused before any request.

2. **The English DART viewer 200s with the single word "Reject" for one filing
   in five.** `englishdart.fss.or.kr/dsbh001/main.do?rcpNo=` looked like the
   ideal `source_url` — it is the same document with FSS's own English labels,
   and no robots.txt governs that host. Measured on 20 real filings from the
   allowlist: 16 rendered, **4 returned a page whose entire body is "Reject"**,
   among them Kia and Korea Gas Corporation. A citation that answers 200 with
   one word is worse than a 404, because a link checker calls it live. So
   `source_url` is the canonical Korean viewer, `dart.fss.or.kr/dsaf001/main.do
   ?rcpNo={rcept_no}`, which is the form OpenDART's own field documentation
   gives for every `rcept_no` and which is stable for the life of the filing.
   Note honestly: **dart.fss.or.kr/robots.txt disallows `/dsaf001/main.do`.**
   Nothing here fetches it — the collector talks only to
   `opendart.fss.or.kr/api/`, which serves no robots.txt — but `link_check.py`
   will record these URLs as `robots` rather than checking them, and that is the
   correct outcome rather than a defect to route around.

3. **A parent files its subsidiary's CEO change under its own name.**
   `대표이사변경 (자회사의 주요경영사항)` is a chaebol-shaped disclosure: the
   listed parent reports a change at a subsidiary, and `corp_name` is the
   PARENT. Miwon Holdings and MAEIL HOLDINGS both filed one in the window.
   Storing it would attribute a subsidiary's change to its parent, and the
   subsidiary is named only inside the document. Refused, by name, in
   REFUSED_REPORT_NAMES — 2 of 261 in 90 days.

4. **Full-width digits break the verbatim-figure guard.** `validate._numbers_in`
   tokenises with `\d`, which matches U+FF10..FF19, and `_normalize_number`
   does not fold them — so `１２３` in a summary and `123` in `raw_text` compare
   unequal and a correct record is discarded silently. Korean filings can carry
   them. `_squeeze` folds full-width digits to ASCII on the way in, and every
   figure in the summary is a substring of the SAME string quoted into
   `raw_text`, so the round trip holds twice over. NFKC would have been the
   obvious fix and is WRONG here: it rewrites U+318D (the ㆍ in
   독립이사의선임ㆍ해임...) to U+119E, silently mangling the report name the
   allowlist matches on.

NAMES. The employer stored is `corp_name_eng` from `company.json`, the
company's OWN registered English name, fetched once per company per run and
cached in memory. It is not a nicety: `company_key` passes Hangul through
unchanged, and the WordPress slug is `[^a-z0-9]+ -> -`, so a Korean key yields
an empty slug and falls back to a percent-encoded one — and HANDOVER.md records
that percent-encoded slugs 404 on this host. A filer whose `corp_name_eng` is
blank is DECLINED rather than romanised: this file invents no transliteration.
The Korean `corp_name` is still quoted into `raw_text`, because that is the
filer's own name and the record should carry it.

WHAT IS NOT STORED, on purpose. `stock_code` is a 6-digit KRX code and is not
written to `ticker`: that column is SEC-authoritative everywhere else in this
tracker (`pipeline/identity.py` resolves it from `company_tickers.json`), and
putting two vocabularies in one column is how a filter starts lying. `adres`
from `company.json` would give a registered address, but a legal seat is not
where an appointment happened and `identity.py` is already the single authority
for `hq_city`. No city is guessed; Korean rows place at country level, as
Indian ones do.

UNPROVEN UNTIL THE FIRST REAL RUN, stated plainly because no authenticated call
has ever been made from here: the exact `list.json` row shape (taken from FSS's
published response spec, not from a response), whether `corp_name_eng` is
populated for every listed filer, and the real request cost of one window. The
documented quota is 20,000 requests a day; a 7-day window is ~8 list pages plus
one `company.json` per distinct employer, so roughly 30 requests a week.
"""

from __future__ import annotations

import os
import re
import time
from datetime import datetime, timedelta, timezone

import requests

LIST_URL = "https://opendart.fss.or.kr/api/list.json"
COMPANY_URL = "https://opendart.fss.or.kr/api/company.json"
VIEWER_URL = "https://dart.fss.or.kr/dsaf001/main.do?rcpNo={rcept_no}"
COLLECTOR = "opendart_korea"
SOURCE_NAME = "DART disclosures (Korea, FSS OpenDART)"

# opendart.fss.or.kr serves no robots.txt (the path 302s to an error page), so
# there is no directive to honour and the default applies. The API asks for no
# Referer and no browser shape, unlike BSE, so the tracker's own agent is used.
USER_AGENT = "TalentIntel/1.0 (+https://asktherecruiter.com)"

# The disclosure detail types this collector reads. Both are values of
# `pblntf_detail_ty` in the published request spec.
#
#   E005  독립사외이사에관한신고 — one report name, every row a leadership event
#   I001  수시공시 — every KRX timely disclosure, so the allowlist below is what
#         makes it usable at all
DETAIL_TYPES = ("E005", "I001")

# The exchange's own report titles, mapped to the ENGLISH label FSS itself
# publishes for each of them. Every English string here was read off the
# official English viewer for a real filing of that type on 2026-07-29
# (englishdart.fss.or.kr/dsbh001/main.do?rcpNo=...), so none of it is a
# translation this file invented:
#
#   20260728900814  대표이사변경                          -> "Change of CEO"
#   20260727800578  대표이사(대표집행임원)변경(안내공시)  -> "Notice on Change of CEO"
#   20260612900609  대표집행임원변경                      -> "Change of Representative
#                                                            Executive Director"
#   20260728000385  독립이사의선임ㆍ해임또는중도퇴임에관한신고
#                                                        -> "Report on the Appointment,
#                                                            Dismissal or Early
#                                                            Retirement of Independent
#                                                            Directors"
#
# A name not on this list is not collected: a value that will not normalise is a
# rejected record, not a new category. Counts are 2026-05-01..2026-07-29.
REPORT_NAMES = {
    "독립이사의선임ㆍ해임또는중도퇴임에관한신고": (          # 150
        "Report on the Appointment, Dismissal or Early Retirement of "
        "Independent Directors"),
    "대표이사변경": "Change of CEO",                          # 79
    "대표이사(대표집행임원)변경(안내공시)": "Notice on Change of CEO",   # 28
    "대표집행임원변경": "Change of Representative Executive Director",   # 4
}

# Named rather than merely absent, so a later reader can see each was a
# decision. Both are titled like a leadership change and are not one we can
# attribute.
REFUSED_REPORT_NAMES = {
    # The listed PARENT reporting a change at a subsidiary it does not name in
    # the title. See trap 3. 2 of 261 in the measured window.
    "대표이사변경 (자회사의 주요경영사항)":
        "a parent reporting an unnamed subsidiary's change",
    # A blank-cheque acquisition vehicle appointing the officers it was
    # incorporated with. A SPAC's board is a formation step, not a hire, and
    # `pipeline/guardrails.py` already refuses SPAC vehicles on the funding side.
    "기업인수목적회사의임원선임결정":
        "a SPAC appointing its own formation officers",
}

# OpenDART endpoints refused after reading their published response spec. Kept
# here because a candidate that cannot work should not sit on the roadmap
# looking merely unstarted.
REFUSED_ENDPOINTS = {
    # 임원현황 — a roster of sitting officers as of `stlm_dt`. No appointment,
    # no appointment date, tenure as free text. An event could only come from
    # diffing two years and inventing the date.
    "exctvSttus.json": "point-in-time roster, states no appointment and no date",
    # 직원현황 — headcount by division and gender, annual or quarterly. Same
    # objection, and it is a workforce level rather than a movement.
    "empSttus.json": "headcount snapshot, not an event",
    # 독립(사외)이사 및 그 변동현황 — the only endpoint with change FIELDS
    # (apnt / rlsofc / mdstrm_resig), and they are period COUNTS with no person
    # and no date. An aggregate is not a record about anybody.
    "outcmpnyDrctrNdChangeSttus.json":
        "aggregate counts of appointments and dismissals, no person, no date",
    # 임원ㆍ주요주주 소유보고 — event-driven and carries `rcept_dt`, but the
    # API exposes no 보고사유 field, so an appointment cannot be told from a
    # share purchase. Reading one as the other would invent the event type.
    "elestock.json": "an ownership filing; the API omits the reason for report",
}

# An amendment is not a second event. DART marks a corrected resubmission by
# prefixing the report name, and this tracker corrects a record by appending a
# revision through `store.revise()`, never by storing a second row. Skipping
# them costs the amendments whose ORIGINAL fell outside the window: 4 of 265
# rows over 90 days, and that is written down rather than hidden.
AMENDMENT_PREFIXES = ("[기재정정]", "[첨부정정]", "[첨부추가]",
                      "[변경등록]", "[정정명령부과]", "[정정제출요구]")

# 법인구분, straight from the response spec. Used only to say which market the
# filer is on, in the record's own body text.
MARKETS = {
    "Y": "the KOSPI market of the Korea Exchange",
    "K": "the KOSDAQ market of the Korea Exchange",
    "N": "the KONEX market of the Korea Exchange",
    "E": "no Korean exchange (a non-listed filer)",
}

PAGE_SIZE = 100         # the documented maximum for page_count
MAX_PAGES = 60          # 6,000 rows per detail type, far past any real window
REQUEST_DELAY = 0.2     # a government API with a 20,000/day documented quota

# How far back a run looks. Seven days on a weekly cron is one cadence plus six
# days of overlap, so a skipped run loses nothing: already-seen URLs are skipped
# before anything is stored, which makes overlap free.
DEFAULT_DAYS = 7

# Measured per ISO week over 2026-05-01..2026-07-29: twelve full weeks ran 12 to
# 49 allowlisted filings, median 19. Five is comfortably below the floor of what
# has ever happened and comfortably above zero, so a run that returns fewer has
# had its report names moved, its detail codes renamed or its key rejected —
# none of which is a quiet week. March is Korea's shareholder-meeting season and
# runs HIGHER, not lower, so the summer measurement is the conservative one.
MIN_ROWS_PER_WINDOW = 5

# The longest report name that is still a headline. Every value in REPORT_NAMES
# is far shorter; this only bounds a name the exchange lengthens later.
HEADLINE_LIMIT = 220

_FULLWIDTH_DIGITS = str.maketrans("０１２３４５６７８９", "0123456789")


class OpenDartError(RuntimeError):
    """A window could not be read, or came back implausibly empty."""


def _headers() -> dict:
    return {"User-Agent": USER_AGENT, "Accept": "application/json"}


def api_key() -> str:
    """The credential, or a loud refusal.

    An unset GitHub secret maps to the EMPTY STRING rather than being absent,
    and OpenDART answers a keyless request with a 302 to an HTML page. Refusing
    here turns that into one readable sentence instead of a JSON parse error
    forty lines later.
    """
    key = (os.environ.get("OPENDART_API_KEY_KR") or "").strip()
    if not key:
        raise OpenDartError(
            "OPENDART_API_KEY_KR is empty or unset. OpenDART answers a keyless "
            "request with a 302 to an HTML error page, so this fails here "
            "rather than as an unexplained parse error later.")
    if not re.fullmatch(r"[0-9a-zA-Z]{40}", key):
        raise OpenDartError(
            f"OPENDART_API_KEY_KR is {len(key)} characters; the published spec "
            f"says the key is 40 alphanumeric characters. Refusing to spend a "
            f"run on a malformed credential.")
    return key


def days_from_env(default_days: int | None = None) -> int:
    """How many days back to read. Set by the workflow, so a backfill is a
    longer window through the same path rather than a script of its own."""
    raw = (os.environ.get("TIT_DART_DAYS") or "").strip()
    if not raw:
        return default_days if default_days is not None else DEFAULT_DAYS
    if not re.fullmatch(r"\d{1,4}", raw):
        raise OpenDartError(
            f"TIT_DART_DAYS holds {raw!r}, which is not a number of days")
    days = int(raw)
    if days < 1:
        raise OpenDartError("TIT_DART_DAYS must be at least 1 day")
    # Without a corp_code the published spec limits a search to three months.
    if days > 90:
        raise OpenDartError(
            f"TIT_DART_DAYS is {days}. OpenDART limits a keyless-of-company "
            f"search to three months, so a longer window silently returns a "
            f"shorter one. Run consecutive 90-day windows instead.")
    return days


def window(days: int, *, today: datetime | None = None) -> tuple[str, str]:
    """The API's date window, in the YYYYMMDD form it insists on."""
    end = today or datetime.now(timezone.utc)
    start = end - timedelta(days=days)
    return start.strftime("%Y%m%d"), end.strftime("%Y%m%d")


def viewer_url(rcept_no: str) -> str | None:
    """The filing's own page on DART, keyed by its receipt number.

    This is the form OpenDART's own field documentation gives for `rcept_no`.
    See trap 2 for why it is not the English viewer.
    """
    clean = (rcept_no or "").strip()
    if not re.fullmatch(r"\d{14}", clean):
        return None
    return VIEWER_URL.format(rcept_no=clean)


def _squeeze(text: str) -> str:
    """Collapse whitespace and fold full-width digits to ASCII.

    The fold is load-bearing, not cosmetic: see trap 4. NFKC would do it and
    would also rewrite the ㆍ that the report-name allowlist matches on, so the
    translation table is deliberately narrow.
    """
    folded = (text or "").translate(_FULLWIDTH_DIGITS)
    return re.sub(r"\s+", " ", folded).strip()


def _date(value: str) -> str | None:
    """'20260728' or '2026-07-28' -> '2026-07-28'."""
    text = re.sub(r"\D", "", (value or "").strip())
    if len(text) != 8:
        return None
    try:
        return datetime.strptime(text, "%Y%m%d").date().isoformat()
    except ValueError:
        return None


def strip_amendment(report_nm: str) -> tuple[str, str | None]:
    """Split a report name into its title and its amendment marker, if any."""
    name = _squeeze(report_nm)
    for prefix in AMENDMENT_PREFIXES:
        if name.startswith(prefix):
            return name[len(prefix):].strip(), prefix
    return name, None


def english_label(report_nm: str) -> str | None:
    """FSS's own English name for this report type, or None if not allowlisted."""
    name, _ = strip_amendment(report_nm)
    return REPORT_NAMES.get(name)


def is_wanted(report_nm: str) -> bool:
    """Whether this row is one of the typed leadership items, unamended."""
    name, amendment = strip_amendment(report_nm)
    if amendment:
        return False
    return name in REPORT_NAMES


def _payload(url: str, params: dict, *, timeout: int, session) -> dict:
    get = (session or requests).get
    resp = get(url, params=params, headers=_headers(), timeout=timeout)
    status_code = getattr(resp, "status_code", 0)
    if status_code != 200:
        raise OpenDartError(
            f"{url} returned HTTP {status_code}. A request with no crtfc_key "
            f"answers 302 with an HTML error page, so check the key is set "
            f"before looking anywhere else.")
    try:
        payload = resp.json()
    except ValueError as exc:
        raise OpenDartError(
            f"{url} did not return JSON: {getattr(resp, 'text', '')[:160]!r}"
        ) from exc
    if not isinstance(payload, dict):
        raise OpenDartError(f"{url} returned a non-object response")

    # HTTP 200 does not mean success here: an unregistered key answers
    # 200 {"status":"010"}. Verified live, keyless, 2026-07-29.
    status = str(payload.get("status") or "")
    message = str(payload.get("message") or "")
    if status == "000":
        return payload
    if status == "013":            # 조회된 데이타가 없습니다 — an empty window
        return {"status": status, "list": [], "total_page": 1}
    if status in {"010", "011", "012", "101", "901"}:
        raise OpenDartError(
            f"OpenDART rejected the credential or the caller (status {status}: "
            f"{message}). Nothing is retried: a bad key does not become good.")
    if status == "020":
        raise OpenDartError(
            f"OpenDART request quota exceeded (status 020: {message}). The "
            f"documented allowance is 20,000 requests a day.")
    if status == "800":
        raise OpenDartError(f"OpenDART is under maintenance (status 800: {message})")
    raise OpenDartError(f"OpenDART returned status {status}: {message}")


def fetch_page(detail_type: str, start: str, end: str, page: int, *, key: str,
               timeout: int = 45, session=None) -> tuple[list[dict], int]:
    """One page of one detail type. Returns (rows, total_page)."""
    payload = _payload(LIST_URL, {
        "crtfc_key": key,
        "bgn_de": start,
        "end_de": end,
        "pblntf_detail_ty": detail_type,
        "page_no": page,
        "page_count": PAGE_SIZE,
        "sort": "date",
        "sort_mth": "desc",
    }, timeout=timeout, session=session)
    rows = payload.get("list")
    if rows is None:
        raise OpenDartError(
            f"{detail_type} returned status 000 with no 'list' key "
            f"(keys: {sorted(payload)[:8]}). The response shape has changed.")
    if not isinstance(rows, list):
        raise OpenDartError(f"{detail_type} returned a non-list 'list' key")
    try:
        total_page = max(1, int(payload.get("total_page") or 1))
    except (TypeError, ValueError):
        total_page = 1
    return rows, total_page


def fetch_company(corp_code: str, *, key: str, timeout: int = 45,
                  session=None) -> dict:
    """One filer's registration record. Read for `corp_name_eng` and nothing
    else — see the NAMES note in the module docstring."""
    return _payload(COMPANY_URL, {"crtfc_key": key, "corp_code": corp_code},
                    timeout=timeout, session=session)


def english_name(corp_code: str, *, key: str, cache: dict, session=None) -> str:
    """The filer's OWN registered English name, or '' if DART holds none.

    Cached per run: one event per company is the normal case, so this is a
    handful of extra requests a week rather than one per row.
    """
    code = re.sub(r"\D", "", str(corp_code or ""))
    if not re.fullmatch(r"\d{8}", code):
        return ""
    if code in cache:
        return cache[code]
    try:
        payload = fetch_company(code, key=key, session=session)
    except OpenDartError as exc:
        # A single filer's registration record failing must not lose the
        # window. The row is declined below because it has no English name,
        # and the count is printed.
        print(f"[{COLLECTOR}] company.json failed for {code}: {exc}")
        cache[code] = ""
        return ""
    name = _squeeze(payload.get("corp_name_eng") or "")
    cache[code] = name
    return name


def _row(entry: dict, english: str) -> dict | None:
    """One list.json row as a raw dict, or None if it is declined.

    `english` is the filer's registered English name, supplied by the caller so
    this stays a pure function that a test can drive without a network.
    """
    report_nm = _squeeze(entry.get("report_nm") or "")
    if not is_wanted(report_nm):
        return None
    label = english_label(report_nm)
    corp_name_kr = _squeeze(entry.get("corp_name") or "")
    company = _squeeze(english)
    url = viewer_url(entry.get("rcept_no") or "")
    published = _date(entry.get("rcept_dt") or "")
    rcept_no = re.sub(r"\D", "", str(entry.get("rcept_no") or ""))
    corp_cls = (entry.get("corp_cls") or "").strip().upper()

    # No English name, no record. Romanising a Korean company name here would
    # be this file inventing an identity, and a Hangul company_key produces a
    # slug that 404s on the live host. See the NAMES note.
    if not (company and corp_name_kr and url and published and rcept_no):
        return None

    market = MARKETS.get(corp_cls, "the Korea Exchange")
    body = (
        f"{company} ({corp_name_kr}) filed this disclosure with the Financial "
        f"Supervisory Service's DART system on {published}, under receipt "
        f"number {rcept_no}. The filer is on {market}. The quoted line above "
        f"is the report title the exchange's own filing system assigned, and "
        f"the Financial Supervisory Service publishes it in English as "
        f"\"{label}\". A Korean listed company must disclose a change of its "
        f"representative director, and must separately report the appointment, "
        f"dismissal or early retirement of an independent director, which is "
        f"what makes these comparable across employers rather than the ones an "
        f"outlet chose to write about. The title states that the change "
        f"happened; it does not state which direction it went, and nothing "
        f"here infers one."
    )

    return {
        # The report title is QUOTED, following collectors/bse_india.py: closing
        # the quote puts a non-space character after any figure, so the
        # magnitude-suffix regex in pipeline/validate.py cannot glue a digit at
        # the end of this line to a letter at the start of the next.
        "raw_text": f"\"{report_nm}\" ({label})\n\n{body}",
        "headline": f"{company}: {label}"[:HEADLINE_LIMIT],
        "source_url": url,
        "source_name": SOURCE_NAME,
        "discovery_url": url,
        "published_date": published,
        "company": company,
        "country": "South Korea",
        # Listed on a Korean exchange, which is what the source IS, except for
        # corp_cls E which is a filer with no listing.
        "employer_type": "public" if corp_cls in {"Y", "K", "N"} else "",
        "report_nm": report_nm,
        "report_label": label,
        "corp_name_kr": corp_name_kr,
        "corp_code": re.sub(r"\D", "", str(entry.get("corp_code") or "")),
        "rcept_no": rcept_no,
        "corp_cls": corp_cls,
        "collector": COLLECTOR,
        "fetched_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }


def collect(queries=None, *, days: int | None = None,
            detail_types: tuple = (), today: datetime | None = None,
            session=None, key: str | None = None) -> list[dict]:
    """Every allowlisted leadership filing in the window.

    `queries` is accepted and ignored so this collector is interchangeable with
    the others in run_collect: there is nothing to search for, the exchange's
    own report titles ARE the population.
    """
    wanted = tuple(detail_types) or DETAIL_TYPES
    crtfc = key or api_key()
    start, end = window(days if days is not None else days_from_env(),
                        today=today)
    out: list[dict] = []
    seen: set[str] = set()
    names: dict[str, str] = {}
    read = 0
    refused = 0
    no_english = 0

    for detail_type in wanted:
        kept = 0
        page = 1
        total_page = 1
        while page <= min(total_page, MAX_PAGES):
            if session is None:
                time.sleep(REQUEST_DELAY)
            rows, total_page = fetch_page(detail_type, start, end, page,
                                          key=crtfc, session=session)
            if not rows:
                break
            read += len(rows)
            for entry in rows:
                name, _ = strip_amendment(_squeeze(entry.get("report_nm") or ""))
                if name in REFUSED_REPORT_NAMES:
                    refused += 1
                    continue
                if not is_wanted(entry.get("report_nm") or ""):
                    continue
                english = english_name(entry.get("corp_code") or "",
                                       key=crtfc, cache=names, session=session)
                item = _row(entry, english)
                if item is None:
                    if not english:
                        no_english += 1
                    continue
                if item["source_url"] in seen:
                    continue
                seen.add(item["source_url"])
                out.append(item)
                kept += 1
            page += 1
        print(f"[{COLLECTOR}] {detail_type}: {kept} filings")

    print(f"[{COLLECTOR}] {start}..{end}: {read} rows read, {len(out)} usable, "
          f"{refused} refused by name, {no_english} declined for no English name")
    if len(out) < MIN_ROWS_PER_WINDOW:
        raise OpenDartError(
            f"{start}..{end} produced {len(out)} filings from {read} rows. "
            f"Korea files 12 to 49 of these a week (measured over twelve weeks "
            f"to 2026-07-29), so this is the report titles having moved, a "
            f"detail code being renamed or the key being refused, not a quiet "
            f"week.")
    return out


def as_classified(item: dict) -> dict:
    """The `classified` half of build_signal, derived rather than generated.

    Every value is read off the response or is a fixed editorial line, so
    nothing on the record can be something a model believed. The report title
    is quoted, never paraphrased, which is also why every figure in the summary
    is present in `raw_text` by construction.
    """
    company = item["company"]
    return {
        "company": company,
        "pillar": "leadership_change",
        # The source does not separate a joiner from a leaver. See the DIRECTION
        # note in the module docstring: `neutral` is the honest answer and
        # `displacement` would put this inside the sibling tracker's scope.
        "signal_direction": "neutral",
        "headline": item["headline"],
        "summary": (
            f"{company} disclosed a leadership change to Korea's Financial "
            f"Supervisory Service through its DART system, filed under the "
            f"report title \"{item['report_nm']}\", which the Supervisory "
            f"Service publishes in English as \"{item['report_label']}\". "
            f"The receipt number of the filing is {item['rcept_no']}. The "
            f"title records that the change occurred and does not state "
            f"whether the officer joined or left."
        ),
        "talent_readthrough": (
            "A Korean listed company must tell the exchange when its "
            "representative director changes, and must separately report the "
            "appointment, dismissal or early retirement of an independent "
            "director. That makes this a complete feed for those two roles "
            "rather than a selective one: it covers the small and mid-cap "
            "employers no outlet writes about on the same basis as the "
            "chaebol. Two limits are worth reading with it. The mandated item "
            "covers the CEO and independent directors, so ordinary inside "
            "directors are elected at a shareholder meeting and do not appear "
            "here. And the report title names the change without naming its "
            "direction, so a departure and an arrival look identical from the "
            "outside; the filing itself distinguishes them and this record "
            "does not guess."
        ),
        "country": "South Korea",
        "employer_type": item.get("employer_type") or "",
        # A statutory disclosure made to the regulator that collects it.
        # infer_confidence caps this at what the host is worth, so it lands at
        # 'verified' only while dart.fss.or.kr is a listed primary source domain.
        "confidence": "verified",
    }
